# Generated by Django 4.0.5 on 2022-06-08 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('writer', models.CharField(max_length=30)),
                ('content', models.TextField()),
            ],
        ),
    ]
